### ISSUE TITLE
Incorrect keyframe count

### ISSUE THREAD

**Issue by schmamps** [chocolateimage/kdenlive_ease_generator#3]
With defaults (1s @ 60fps) this becomes `range(0, 61)` and and `len(t) == 61`

https://github.com/chocolateimage/kdenlive_ease_generator/blob/6a349c3480c0958c5f2dba7a0264239f08c6d0a5/ease_generator.pyw#L156
https://github.com/chocolateimage/kdenlive_ease_generator/blob/6a349c3480c0958c5f2dba7a0264239f08c6d0a5/ease_generator.pyw#L166

One of these must be more correct:

```py
# calculate 60 easing steps
for i in range(0, max_range)...

# throw out first step
';'.join(t[1:])

# throw out last step
";".join(t[:max_range))

**Comment by chocolateimage** [comment]
Fixed in this commit:
https://github.com/chocolateimage/kdenlive_ease_generator/commit/62709463b41c5b9db5993a423dae3a3136454868
