### ISSUE TITLE
Awkward notation for duration

### ISSUE THREAD

**Issue by schmamps** [chocolateimage/kdenlive_ease_generator#4]
Without going straight to `HHMMSS,FF` notation like Kdenlive, it would be nice to at least use the decimal place for an absolute number of frames, e.g. `SS.FF`, instead of fractions of a second.

## Example

```py
fps = 60
duration = 1.05

# curren
keyframe_count = fps * duration  # result: 90

# proposed
keyframe_count = (fps * floor(duration)) + (duration % 1)  # result: 65
```

## Changes

The decimal precision of `numDuration` must be `len(str(numFps))`

**Comment by chocolateimage** [comment]
I agree, should I add two radio buttons next to the duration?

**Comment by chocolateimage** [comment]
I added the option to commit https://github.com/chocolateimage/kdenlive_ease_generator/commit/48d723329ee31a280083d74a2ddc978e3bde04bc
