### ISSUE TITLE
[Feature] Add ability to save and load presets

### ISSUE THREAD

**Issue by hyuri** [chocolateimage/kdenlive_ease_generator#7]
Hi!

It would be nice if we could save and load presets. Perhaps a .json file?

That way we can save a few standard eases we use often on every project and easily load them for every project.

**Comment by chocolateimage** [comment]
Added it in commit https://github.com/chocolateimage/kdenlive_ease_generator/commit/5aabf2b45e904e92d44ed1e0d011f268da8e9080

**Comment by hyuri** [comment]
Awesome! Thank you!
