### ISSUE TITLE
Feature Suggestion: Import existing keyframes

### ISSUE THREAD

**Issue by candidexmedia** [chocolateimage/kdenlive_ease_generator#9]
Hi! Thank you again for making this. It's a great fix until Kdenlive implements it in the program.

I'd like to suggest the ability to import two keyframes into the ease generator, and have the ease generator fill in the required position, size, keyframes based on the easing type selected.

For instance, let's say I add a Transform effect to a Colour clip:

![image](https://github.com/chocolateimage/kdenlive_ease_generator/assets/95003834/d110d33c-464d-4a5e-a672-23745d2a7627)

And I add a keyframe to mark where I want the rectangle to end up:

![image](https://github.com/chocolateimage/kdenlive_ease_generator/assets/95003834/b975308e-f364-4b38-b77d-464a0261f1b2)

I'd love to be able to select "Copy All Keyframes to Clipboard" and paste it directly into the Ease Generator, filling out the position, size, opacity, duration, etc.:

![image](https://github.com/chocolateimage/kdenlive_ease_generator/assets/95003834/5eba57e8-7a06-480e-b076-d1315d15917e)

This was, it's as simple as setting two keyframes, copying them at once, pasting into the Generator once, setting an easing, copying from the Generator, and importing back into Kdenlive.

**Comment by chocolateimage** [comment]
Added in https://github.com/chocolateimage/kdenlive_ease_generator/commit/5a12c1139d42384da41a19efe263333afa421845

Click on "Copy All Keyframes to Clipboard" and then click on both paste buttons.
